# Generated by Django 3.0.7 on 2020-06-27 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('org_id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Organization ID')),
                ('name', models.CharField(max_length=100, verbose_name='Organization Name')),
                ('email', models.EmailField(max_length=254)),
                ('org_picture', models.ImageField(upload_to='org_picture/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Post ID')),
                ('title', models.CharField(max_length=100)),
                ('banner', models.ImageField(upload_to='post_banners/%Y/%m/%d/')),
                ('type', models.CharField(choices=[('VIDEO', 'Video'), ('TEXT', 'Text')], max_length=5)),
                ('link', models.URLField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_points', models.IntegerField(default=0)),
                ('profile_picture', models.ImageField(upload_to='profile_picture/%Y/%m/%d/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Event ID')),
                ('name', models.CharField(max_length=100, verbose_name='Event Name')),
                ('time', models.DateTimeField()),
                ('duration', models.TimeField()),
                ('content', models.TextField()),
                ('banner', models.ImageField(upload_to='event_banners/%Y/%m/%d/')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Organization')),
            ],
        ),
    ]
