# Generated by Django 3.0.7 on 2020-06-27 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Event ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('experience_points', models.IntegerField(default=0)),
                ('profile_picture', models.ImageField(upload_to='profile_picture/%Y/%m/%d/')),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='org_id',
            new_name='managed_by',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='organization',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='posted_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.User'),
            preserve_default=False,
        ),
    ]
