# Generated by Django 3.0.7 on 2020-06-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200628_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='badges',
            field=models.ManyToManyField(blank=True, to='backend.Badge'),
        ),
    ]
